In [3]:
import pandas as pd
import os

In [4]:
csv_Path = os.path.join("/Users/macbookpro/Desktop/For Graduation/Test","Data21.csv")
MyData = pd.read_csv(csv_Path,parse_dates = ['ad_date'])
MyData

/Users/macbookpro/Documents/naser_python/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,make,model,type,#pass,year,price,color,fuel,history,gear,...,windows,url,alarm,ac,radio_cd,sunroof,leatherـchair,centralـLock,magnesium_wheels,air_bag
0,Volkswagen,Passat,sedan,5,1999,28500.0,dark blue,petrol,private,automatic,...,electric,https://shobiddak.com/cars/432099,1,1,0,1,0,1,0,0
1,Volkswagen,Passat,sedan,5,2001,43000.0,gray,petrol,private,automatic,...,electric,https://shobiddak.com/cars/432100,1,1,1,0,0,1,0,1
2,hyundai,Accent,sedan,5,2014,68000.0,white,petrol,private,automatic,...,manual,https://shobiddak.com/cars/432104,1,1,1,0,1,1,1,1
3,kia,Pride(rio),__sedan/hatch__,5,2008,49000.0,silver,diesel,private,manual,...,electric,https://shobiddak.com/cars/432105,1,1,1,0,0,1,1,1
4,BMW,3 Series,sedan,5,1986,30000.0,blue,petrol,private,manual,...,electric,https://shobiddak.com/cars/432107,1,0,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201675,Mercedes,C-Class,sedan,5,2002,50000.0,brown,diesel,taxi,automatic,...,electric,https://shobiddak.com/cars/679985,0,1,1,0,1,1,1,1
201676,Mercedes,Sprinter,van,7,1989,25000.0,white,diesel,private,manual,...,manual,https://shobiddak.com/cars/570091,0,0,0,0,0,0,0,0
201677,Mercedes,Atego,truck,2,1995,NaN,white,diesel,private,manual,...,manual,https://shobiddak.com/cars/616383,0,0,0,0,0,0,0,0
201678,Mercedes,Atego,truck,3,1996,85000.0,white,diesel,Commercial,manual,...,manual,https://shobiddak.com/cars/463031,1,1,1,1,0,1,0,0
201679,Mercedes,Sprinter,van,7,2008,80000.0,white,diesel,Commercial,manual,...,electric,https://shobiddak.com/cars/481989,1,1,1,0,0,1,0,1

In [19]:
MyData["Days_Live"]=-999

In [20]:
MyData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201680 entries, 0 to 201679
Data columns (total 26 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   make              201680 non-null  object
 1   model             200857 non-null  object
 2   type              201680 non-null  object
 3   #pass             201680 non-null  int64
 4   year              201680 non-null  int64
 5   price             201542 non-null  float64
 6   color             201680 non-null  object
 7   fuel              201680 non-null  object
 8   history           201680 non-null  object
 9   gear              201680 non-null  object
 10  engine_size       201680 non-null  object
 11  Kilometers        118321 non-null  float64
 12  owners            150351 non-null  float64
 13  ad_date           201680 non-null  datetime64[ns]
 14  payment_method    201680 non-null  object
 15  windows           201680 non-null  object
 16  url               201680 non-null  object
 17  alarm             201680 non-null  int64
 18  ac                201680 non-null  int64
 19  radio_cd          201680 non-null  int64
 20  sunroof           201680 non-null  int64
 21  leatherـchair     201680 non-null  int64
 22  centralـLock      201680 non-null  int64
 23  magnesium_wheels  201680 non-null  int64
 24  air_bag           201680 non-null  int64
 25  Days_Live         201680 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(11), object(11)
memory usage: 40.0+ MB

In [22]:
Count = 0
for row in range(0,MyData.shape[0]):
    date1 = date(MyData.at[row,"year"], 1, 1)
    date2 = MyData.at[row,"ad_date"].date()
    MyData.at[row,"Days_Live"] = (date2-date1).days
    Count = Count + 1
    
print("The Row is Affected was ---->",Count)

The Row is Affected was ----> 201680

In [24]:
MyData.head()

,make,model,type,#pass,year,price,color,fuel,history,gear,...,url,alarm,ac,radio_cd,sunroof,leatherـchair,centralـLock,magnesium_wheels,air_bag,Days_Live
0,Volkswagen,Passat,sedan,5,1999,28500.0,dark blue,petrol,private,automatic,...,https://shobiddak.com/cars/432099,1,1,0,1,0,1,0,0,6472
1,Volkswagen,Passat,sedan,5,2001,43000.0,gray,petrol,private,automatic,...,https://shobiddak.com/cars/432100,1,1,1,0,0,1,0,1,5741
2,hyundai,Accent,sedan,5,2014,68000.0,white,petrol,private,automatic,...,https://shobiddak.com/cars/432104,1,1,1,0,1,1,1,1,993
3,kia,Pride(rio),__sedan/hatch__,5,2008,49000.0,silver,diesel,private,manual,...,https://shobiddak.com/cars/432105,1,1,1,0,0,1,1,1,3185
4,BMW,3 Series,sedan,5,1986,30000.0,blue,petrol,private,manual,...,https://shobiddak.com/cars/432107,1,0,1,1,1,1,1,0,11219

In [25]:
MyData.to_csv("Data22.csv")

In [16]:
from datetime import date
# Driver program
date1 = date(MyData.at[0,"year"], 1, 1)
date2 = MyData.at[0,"ad_date"].date()
print((date2-date1).days, "days")

6472 days