In [1]:
import pandas as pd
from googletrans import Translator

In [2]:
%%time
df=pd.read_excel("/Users/macbookpro/Desktop/For Graduation/T3Test.xlsx")

CPU times: user 1min 45s, sys: 750 ms, total: 1min 45s
Wall time: 1min 46s

In [3]:
df["car_name_t"]=""

In [4]:
translator = Translator()

In [5]:
%%time
for row in range(0,10):
    name=df.at[row,"car_name"].strip()
    df.at[row,"car_name_t"] = translator.translate(name , dest ='en').text

CPU times: user 90 ms, sys: 15.3 ms, total: 105 ms
Wall time: 5.53 s

In [6]:
df.head(10)

,Unnamed: 0,car_name,year,price,color,fuel,history,gear,engine_size,Kilometers,...,url,alarm,ac,radio_cd,sunroof,leatherـchair,centralـLock,magnesium_wheels,air_bag,car_name_t
0,0,فولكسفاجن باسات,1999,28500,dark blue,petrol,private,automatic,1600,NaN,...,https://shobiddak.com/cars/432099,1,1,0,1,0,1,0,0,Volkswagen Passat
1,1,فولكسفاجن باسات,2001,43000,gray,petrol,private,automatic,1600,100000,...,https://shobiddak.com/cars/432100,1,1,1,0,0,1,0,1,Volkswagen Passat
2,2,هونداي اكسنت,2014,68000,white,petrol,private,automatic,1500,45000,...,https://shobiddak.com/cars/432104,1,1,1,0,1,1,1,1,Hyundai Accent
3,3,كيا برايد,2008,49000,silver,diesel,private,manual,1500,NaN,...,https://shobiddak.com/cars/432105,1,1,1,0,0,1,1,1,Kia Pride
4,4,بي ام دبليو 316,1986,30000,blue,petrol,private,manual,1600,NaN,...,https://shobiddak.com/cars/432107,1,0,1,1,1,1,1,0,BMW 316
5,5,فولكسفاجن باسات,2010,960000,black,diesel,private,automatic,2000,195000 km,...,https://shobiddak.com/cars/432108,1,1,1,0,0,1,1,1,Volkswagen Passat
6,6,ستروين بيكاسو C4,2013,100000,gray,diesel,private,automatic,1600,NaN,...,https://shobiddak.com/cars/432109,1,1,1,0,0,1,1,1,Citroen Picasso C4
7,7,بي ام دبليو X5,2008,260000,green,diesel,private,automatic,3000,220000,...,https://shobiddak.com/cars/432111,1,1,1,1,1,1,1,1,BMW X5
8,8,فولكسفاجن كبينة,1985,35000,yallow,diesel,Commercial,manual,1900,NaN,...,https://shobiddak.com/cars/432113,0,0,0,0,1,0,0,0,Volkswagen booth
9,9,سكودا اوكتافيا,2015,113000,red,petrol,private,automatic,1400,NaN,...,https://shobiddak.com/cars/432115,0,1,0,1,0,1,1,1,Skoda Octavia